### ISSUE TITLE
Unzip directory 7z file, the directory is missing

### ISSUE THREAD

**Issue by hlllmr1314** [mdejong/lzmaSDK#5]
I hava a directory 7z file, when I execute your program，the directory is missing.

I want to be "/tmp/Extract7z/a/b/c/xx.mp3"
But now the results is  "/tmp/Extract7z/xx.mp3"

what should i do？

**Comment by mdejong** [comment]
Are you using this API to do the extraction?

// Extract all the contents of a .7z archive directly into the indicated dir.
// Directory structure is ignored if preserveDir is false.

+ (NSArray*) extract7zArchive:(NSString*)archivePath
                      dirName:(NSString*)dirName
                  preserveDir:(BOOL)preserveDir;

You would need to call this method with preserveDir:TRUE in order to extract with fully qualified path names. If you do not pass TRUE for the argument, then all files are extracted and placed into the named directory.

**Comment by hlllmr1314** [comment]
You're right！thank you
